spring:
  profiles:
    active: prod
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss

app:
  constants:
    bot:
      bot-name: Help-Bot
      bot-token: ${BOT_TOKEN}
